### ISSUE TITLE
return diffs only

### ISSUE THREAD

**Issue by iraizo** [romankoblov/prettydiff#12]
Is there a way I can only print diff_lines if theres an actual diff?

**Comment by mwcz** [comment]
Actually, [set_diff_only](https://docs.rs/prettydiff/0.6.1/prettydiff/text/struct.LineChangeset.html#method.set_diff_only) is the way.

**Comment by jiacai2050** [comment]
set_diff_only only works for side-by-side diff, not used in `format`, I prefer to apply in format too, since equal lines are quite verbose.

Also, I find `SliceChangeset` will display equal line like `skip(N)`, it's best `LineChangeset` follow this style, but include line numbers.
