### ISSUE TITLE
library has unnecessary structopt dependency

### ISSUE THREAD

**Issue by scottlamb** [romankoblov/prettydiff#6]
The binary uses structopt, but the library doesn't. It's annoying for other programs using the library to have the extra structopt dependency. (My program depends on structopt anyway, but 0.3 rather than prettydiff's 0.2, so I end up with two copies of structopt in my dependency tree.)

Looks like there are several different ways one can structure a project to avoid this unnecessary dependency, as described here: https://stackoverflow.com/questions/35711044/how-can-i-specify-binary-only-dependencies What's your favorite?

**Comment by cecton** [comment]
Yes I found the same issue. But I'm not sure if the project is still alive. 2 years since the last update
