### ISSUE TITLE
`prettytable` dependency does not compile on Windows

### ISSUE THREAD

**Issue by danielhenrymantilla** [romankoblov/prettydiff#9]
Hey, thanks for this crate, the output it yields is quite nice 🙂

Alas, this crate currently fails to compile on Windows: https://github.com/danielhenrymantilla/prettyplease-cli/runs/5058081311?check_suite_focus=true

While fixing that might require a non-negligible effort, a simpler workaround would be to make `prettytable` an optional dependency as well, since I'm only using the `Display` impl of the `prettydiff`

**Comment by romankoblov** [comment]
I don't have any computer with Windows, so I cannot test it. However, if you can send pull request (for example with optional, but enabled by default prettytable dependency, so it won't change current default behaviour), I will merge it.

**Comment by romankoblov** [comment]
merged && released
